# Generated by Django 3.1 on 2020-09-12 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BPM', models.IntegerField()),
                ('FREQ', models.IntegerField()),
                ('BREATH', models.IntegerField()),
                ('BMI', models.IntegerField()),
                ('FAT', models.IntegerField()),
                ('MDF', models.IntegerField()),
                ('MNF', models.IntegerField()),
                ('RMS', models.IntegerField()),
                ('RRMS', models.IntegerField()),
                ('ALPHA', models.IntegerField()),
                ('BETA', models.IntegerField()),
                ('DELTA', models.IntegerField()),
                ('THETA', models.IntegerField()),
            ],
        ),
    ]
